### ISSUE TITLE
Request: Improve log directive documentation

### ISSUE THREAD

**Issue by mqus** [caddyserver/website#116]
I had a caddyfile that roughly did the following:
```
example.com {
	reverse_proxy [...]
	log {
		output file /var/log/caddy/example.com.log
	}
}

example.com/subdir {
	reverse_proxy [other endpoint]
	log {
		output file /var/log/caddy/example.com-subdir.log
	}
}
```

But everything got logged to the file of the first site block (regardless of ordering, its always the most general block). This does not seem to be a bug but more of a missing feature so far (I found e.g. https://github.com/caddyserver/caddy/issues/3418), so it would be nice if this would be documented better. 

I'm not sure on the wording and where to best put it or I would have opened a small PR myself. But as a reader, I would expect it to be mentioned on the page for the log directive at least.

Thank you!

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

The problem is that access logging can only be based on the hostname currently. It would be very complicated to make it based on more than that. If you look at the `caddy adapt` command's output, you'll see what the underlying logging config looks like.

If I had my way, I would deprecate `/subdir` path matchers in the site address in favor of doing it with `handle` instead, in which case it would be more obvious how things behave.

Alternative way to write your config, which is less ambiguous:

```
example.com {
	handle /subdir* {
		reverse_proxy [other endpoint]
	}

	handle {
		reverse_proxy [...]
	}

	log {
		output file /var/log/caddy/example.com.log
	}
}
```

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community) first. It's typically easier to figure out an issue there first, then turn it into an issue depending on the outcome. And don't forget to fill out the thread template!

**Comment by mqus** [comment]
I'm not requesting to fix the issue, but to document it. And I think this should be handled here. I did look at the output of the caddy adapt command and that is exactly why I think this is a documentation issue, not exactly something wrong with caddy itself.

**Comment by mholt** [comment]
I already updated the docs locally and will push them soon. That's why I closed the issue.

**Comment by mqus** [comment]
Ah right, thank you very much :)

**Comment by mholt** [comment]
Here you go: https://github.com/caddyserver/website/commit/94a7c5f1cd5cb1912fbcdbf1144a6f4915ef6965#diff-adc9e3188661e6571c1013eb6cbf382d182e38d3666415f3b4507d11589adef7

**Comment by king5300** [comment]
[]()
