### ISSUE TITLE
Plugin documentation not recognized

### ISSUE THREAD

**Issue by ale-rinaldi** [caddyserver/website#130]
Hello,
I'm the author of a Caddy module that is listed on the official download page: https://github.com/porech/caddy-maxmind-geolocation

However, unlike the other plugins, the documentation is not appearing. When I first submitted the module, the documentation was not there; however after adding it I tried rescanning and even removing the package and submitting it again, but no luck.

Is this something wrong on my repo, or is it a parsing issue?

Thanks!

**Comment by francislavoie** [comment]
Unfortunately, there's a known issue with the system backing the documentation parsing from external modules. It seems to just not actually update the docs correctly on rescan.

But I do see your module's docs here: https://caddyserver.com/docs/modules/http.matchers.maxmind_geolocation, although it may be outdated because of the issue I mentioned. It also appears here (in the list of matcher modules): https://caddyserver.com/docs/json/apps/http/servers/routes/match/

**Comment by ale-rinaldi** [comment]
Hello,

yes, I see the documentation but each field has "There are no docs for this property", even if the fields are documented.

Thanks for your answer, it was just to be sure it's not an issue by my side 👍  hope this will be updated at a certain time then.

Thanks again

**Comment by mholt** [comment]
Yeah, sorry, I need to get around to fixing that. It's a very manual "delete from the DB, then restart the Caddy service" process, so it's tedious and I try to avoid it, haha. One problem is I don't know how to totally solve it yet, so I need some time to work on it.

**Comment by mholt** [comment]
I've been working on this pretty heavily this week and hope to have something to show by next week, next month at the latest.

**Comment by mholt** [comment]
Oh, so this should be working now. "Rescan" should actually work more as expected.

**Comment by ale-rinaldi** [comment]
Yup, that worked! Thank you @mholt :)
