### ISSUE TITLE
Want to add third party module

### ISSUE THREAD

**Issue by kilosonc** [caddyserver/website#132]
hi, I have a third party module want to add to docs, but only found standard module here. Where should I put my module docs, thanks

**Comment by kilosonc** [comment]
actually, there's no content in module page when I run a server locally

**Comment by francislavoie** [comment]
The website repo doesn't have the JSON docs because it's driven by an API that's run separately.

To add register your module, make an account on https://caddyserver.com and claim your package in the account page. That'll also add it to the download page which acts as a listing of all the available plugins.

**Comment by kilosonc** [comment]
ok, thanks

**Comment by kilosonc** [comment]
sorry, but how can I add docs for my module

**Comment by francislavoie** [comment]
It's automatically pulled from the godocs of your module (the comments in your code before your module struct and its fields).

There is a known issue with the site though where resyncs aren't working though. So for the time being, best thing to do is just make your README on GitHub contain all the relevant details for your users.

**Comment by kilosonc** [comment]
got it, thanks
