### ISSUE TITLE
Debian Install GPG Key URL returns 404

### ISSUE THREAD

**Issue by dli7319** [caddyserver/website#134]
The URL in `install.md` https://dl.cloudsmith.io/public/caddy/stable/cfg/gpg/gpg.155B6D79CA56EA34.key returns 404. \
The URL https://dl.cloudsmith.io/public/caddy/stable/gpg.155B6D79CA56EA34.key on the [cloudsmith website](https://cloudsmith.io/~caddy/repos/stable/setup/#formats-deb) works fine. \
Perhaps this can be updated?

**Comment by francislavoie** [comment]
Strange... @lskillen did something change?

**Comment by francislavoie** [comment]
Huh, strange. Looks like the `/cfg/gpg` paths suddenly work again. https://caddy.community/t/gpg-key-not-found-for-debian/11356

**Comment by lskillen** [comment]
@mholt @francislavoie This is our fault!

We had shipped a change to reduce the length of the keys, config and bash setup URLs (a big request from the community). We had intended to keep the existing URLs for backwards compatibility, and this mostly worked, except for the "keys" based one.

We rolled out a hotfix to restore the compatibility, so that explains your "it stopped working, but now it is working" situation. So huge apologies for both the temporary breakage and the confusion. 🙇‍♂️

We try not to remove backwards compatibility if possible, and if we have to, we would do it with significant notice! On the upside, you have some shorter URLs to use now. 😅

**Comment by francislavoie** [comment]
Appreciate the follow-up! ❤️

**Comment by mholt** [comment]
It happens; we just had a few people asking. Thanks for the quick fix!

**Comment by lskillen** [comment]
You're welcome folks! Btw, you can also use `gpg.key` in the GPG key URL instead of `gpg.[fingerprint].key` and it'll always point to the latest (plus it's a bit shorter). :-)

**Comment by francislavoie** [comment]
Oooh, thanks for the 🔥 hot tip

https://github.com/caddyserver/website/commit/930109ec3399035c4870a6c6a673537ca4813960

**Comment by francislavoie** [comment]
@lskillen Looks like the `config.deb.txt` still needs the query params, is that still being looked into? (i.e. allowing not specifying it to get `any-version`)
No big deal, but it would be noice 😄

**Comment by lskillen** [comment]
@francislavoie I just raised a PR with the team here to allow you shorten that again. :-)

From:
https://dl.cloudsmith.io/public/caddy/testing/config.deb.txt?distro=debian&version=any-version

To:
https://dl.cloudsmith.io/public/caddy/testing/debian.deb.txt

The `debian.deb` bit looks a bit silly, but we've got some (convoluted) reasons for it. Might be fixed at some later date!

I'll ping you again when it ships (probably tomorrow).

**Comment by francislavoie** [comment]
![](https://media.giphy.com/media/8fen5LSZcHQ5O/giphy.gif)

**Comment by lskillen** [comment]
@francislavoie This is ready now. Get ready to rock:
https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt

Unfurled:

```
# Source: Cloudsmith (support@cloudsmith.io)
# Repository: Caddy / stable
# Description: Fast, multi-platform web server with automatic HTTPS

deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
```
