### ISSUE TITLE
Cannot access to https://caddy.community

### ISSUE THREAD

**Issue by lefuturiste** [caddyserver/website#210]
With firefox: Error with ssl
![image](https://user-images.githubusercontent.com/20988163/152647361-db6ddac0-0a23-4cb4-b9b2-d45ce6b3dcff.png)

With chromium: timeout

**Comment by mholt** [comment]
Wait a sec, the same thing happens on MY mobile network too.

I thought it was just me. So maybe there's a problem with the forum. I'll have to look into it.

**Comment by mholt** [comment]
@lefuturiste Who is your ISP? Does your mobile device have an IPv6 address?

**Comment by mholt** [comment]
Finally got it working for me on my mobile network, at least (no thanks to DigitalOcean). Their default cloud-init kept breaking the IPv6 interface so I had to manually override it with the proper settings.

**Comment by lefuturiste** [comment]
Yes it's working for me now. Thanks!

**Comment by lefuturiste** [comment]
@mholt What was the particular issue that you faced with the IPv6 config of DO?

**Comment by lefuturiste** [comment]
And what is so special about mobile network to fail with IPv6? I would expect that if the IPv6 is broken on the server side then the non-cellular network should be fine?

**Comment by mholt** [comment]
@lefuturiste I don't remember the details at this point, but for whatever reason their cloudinit was nuking the IPv6 interface on the machine so it only worked with IPv4. I remember doing something with `/etc/netplan/50-cloud-init.yaml` I think, and some other obscure kernel tweaks... maybe I just ended up disabling the cloud init. There's a file I created on Feb. 9 called `/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg` that has `network: {config: disabled}` in it as its only contents.

I didn't really know what I was doing, but by disabling DO's scripts things are working again.

The mobile network was IPv6-enabled, whereas my home connection wasn't. So it worked fine on IPv4 enabled networks but for whatever reason my mobile network wouldn't use IPv4. Probably because IPv6 did route successfully, just didn't connect through to the machine successfully.
