### ISSUE TITLE
500 When doc page not found

### ISSUE THREAD

**Issue by fagci** [caddyserver/website#213]
Somewhy https://caddyserver.com/docs/abrakadabra returns 500 for me, but in local environment its ok (404).
Pulled latest commit.
`Caddy v2.4.6`

**Comment by francislavoie** [comment]
Yeah, we just never implemented error handling or error pages for the website yet.

This is just the https://caddyserver.com/docs/caddyfile/directives/templates directive triggering an error because it can't find a markdown page to load. 

Duplicate of https://github.com/caddyserver/website/issues/35

**Comment by mholt** [comment]
The docs on tip return a 404:

https://github.com/caddyserver/website/blob/ec2cf03fadc72be3161974a1467eaa947361487f/src/docs/index.html#L4

This feature is already implemented but only supported when Caddy is built with the latest version of Go, as propagating error values was only a recent fix upstream in the standard library's `text/templates` package.
