### ISSUE TITLE
small problem when rendering markdown links

### ISSUE THREAD

**Issue by paulovieira** [caddyserver/website#217]
Can be seen in https://caddyserver.com/docs/caddyfile/directives/handle, in _"directives within a route are not re-ordered"_

This is how I see it:

![Screenshot_2022-03-09_23-00-48](https://user-images.githubusercontent.com/2184309/157553676-26a4cb73-4401-494a-b6ac-30cbb9a411ec.png)

The markdown code seems correct. The problem is probably caused by the presence of the dash in the link.

**Comment by francislavoie** [comment]
I think this is just because the website is using an outdated build of Caddy which has an old version of goldmark with a bug. The actual markdown looked fine to me :thinking:

**Comment by mholt** [comment]
Opened issue upstream: https://github.com/yuin/goldmark/issues/284

**Comment by mholt** [comment]
Huh, well apparently it was fixed in the latest version of Goldmark (which we already recently updated), and just bumping the version solved it for me. (Caddy website was already using the latest version of Caddy, it was just that we hadn't updated the goldmark version.) Fixed in https://github.com/caddyserver/caddy/commit/bf6a1b75385da101bad110926c7f2b5f25395959
