### ISSUE TITLE
Website caddyserver.com does not load

### ISSUE THREAD

**Issue by Desnoo** [caddyserver/website#253]
I discovered today that the website https://caddyserver.com/v2 does not load and fails with a ERR_CONNECTION_REFUSED error when opened with Google Chrome  (104.0.5112.79).
I hope this is the correct channel to inform you about it.

**Comment by Desnoo** [comment]
The website is just working again. I will close the ticket.

**Comment by mholt** [comment]
@Desnoo Thanks for the report, I also woke up to an email about it. :sweat_smile: 

Looks like our server had a huge flood of connections and the humble little DigitalOcean droplet couldn't handle it: CPU, memory, and disk I/O surged as it tried to respond with the Caddy homepage to all the clients at once. The logs show that Caddy was doing its job, the hardware just wasn't capable (it is running on shared hardware on a virtual machine, after all).

Although I generally recommend against doing this at least for new sites (because systemd is unable to be configured to restart only on certain exit codes, and restarting on exit code 1 could lead to problems), I set `Restart=on-failure` in our systemd unit file so that the server will come back up next time this happens. Hopefully that will help minimize downtime in the event of a similar DoS attack.
