### ISSUE TITLE
Reverse proxy HTTPS section should state that '{upstream_hostport}' is a literal

### ISSUE THREAD

**Issue by gravelld** [caddyserver/website#279]
At https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#https we have this snippet:

```
reverse_proxy https://example.com {
	header_up Host {upstream_hostport}
}
```

It took me some time to realise that `{upstream_hostport}` was _not_ a placeholder for the literal value of the upstream host's port. Once I changed it to literally `{upstream_hostport}` it worked fine.

I realise there's [documentation for the syntax](https://caddyserver.com/docs/caddyfile/directives#syntax) but (1) curly brackets aren't mentioned and (2) most visitors won't back up to review them.

**Comment by francislavoie** [comment]
But it _is_ a placeholder. See https://caddyserver.com/docs/caddyfile/concepts#placeholders

The docs assume you've read the Concepts page at least, to understand the basics of how the Caddyfile works.

Otherwise, we'd have to mention "we're using a placeholder here, go read about it over here" which would have to be written basically _everywhere_. It would be way too noisy and repetitive.

**Comment by mholt** [comment]
Thanks for the feedback.

As you said, we do document the syntax, and curly braces aren't mentioned there because they aren't part of the syntax documentation -- thus they are literal.

We're always open to improvements but I think explaining the "Caddyfile syntax syntax" on every page isn't really a feasible solution. I'm not sure what more we can do than expect that users read how to read the docs. (We follow a fairly standard syntax btw, so a lot of the `< >` and `[ ]` notation should be familiar to anyone who has read syntax docs before for anything like CLI tools and other languages or specifications.)

**Comment by gravelld** [comment]
> But it is a placeholder

Hah, well there's me not being specific enough; I meant a placeholder _I was supposed to substitute_, not Caddy at runtime.

English is hard...

Perfectly acceptable to close this as WONTFIX, just wanted to feed back in case it was helpful.
