### ISSUE TITLE
Download with caddy-security plugin

### ISSUE THREAD

**Issue by greenpau** [caddyserver/website#287]
Plugin download build requires specifying “replace” directive. Please see https://github.com/greenpau/caddy-security/issues/196#issuecomment-1367649033 for the context.

the gist is an upstream dependency had a security issue requiring addressing it with “replace” directive. Now, I suspect that “caddy-security” will not download because the replace directive will not be added to the build.

@mholt , is it something you can help addressing in the download website?

**Comment by mholt** [comment]
(This might need to be transferred to `xcaddy`, but for now I've moved it to `website` since the website sets up parameters with which to invoke `xcaddy`. I dunno...)

So is the problem that xcaddy is not honoring the `replace` directive in go.mod? If so, maybe that needs to be fixed in xcaddy (although, I seem to remember a reason to _not_ automatically honor those... what was it... hmm).

**Comment by greenpau** [comment]
> So is the problem that xcaddy is not honoring the replace directive in go.mod?

@mholt , the replace directive is both in caddy-security and go-authcrunch. It look like one of these is not propagating.

**Comment by mohammed90** [comment]
Go modules ecosystem by design does not propagate `replace` because they are supposed to be valid only within the module for local development. See https://github.com/golang/go/issues/30354#issuecomment-466479708.

Xcaddy will not be able to honor them without either: parsing go.mod, or the user explicitly specifying them. Xcaddy can do replacements already but it needs to be told, `--with <host>/<module>=<replacement-host>/<replacement-mo>`.

The question is: Should this knob be exposed to the module developers on the portal?

**Comment by mholt** [comment]
Ah, that's right.

I think, typically, the _proper_ fix for problems like that (we encountered something like this once too) is to fork the problematic repository until it gets its versioning fixed. Using the forked version won't require a replace.

**Comment by greenpau** [comment]
> is to fork the problematic repository until it gets its versioning fixed. 

@mholt , that’s what I did. Then added replace to caddy-security. However, xcaddy is not aware of the replace directive.

**Comment by mholt** [comment]
@greenpau Right, but I mean, instead of using `replace` in go.mod, you literally will use your fork in your code (import your fork's package, not the original one), instead of setting a `replace` in go.mod, does that make sense?

**Comment by greenpau** [comment]
> you literally will use your fork in your code (import your fork's package, not the original one), 

@mholt , I did that. We are good. I am also working with the upstream maintainer to resolve the issue.

**Comment by mholt** [comment]
Cool, that sounds great!! Thanks Paul :)
