### ISSUE TITLE
Download with multiple plugins causes error

### ISSUE THREAD

**Issue by medariox** [caddyserver/website#31]
I don't seem to be able to download caddy with multiple plugins from caddyserver.com.

```https://caddyserver.com/download/linux/amd64?plugins=http.filemanager,http.webdav```
> provisioning build environment: exit status 1

Works just fine with a single plugin.
Thanks!

**Comment by mholt** [comment]
This error happens for any build configuration that isn't already cached. This is due to a breaking change in a vendored dependency (see https://github.com/lucas-clemente/quic-go/issues/797). Go before version 1.9 does not ignore the vendor folder when running `./...` such as `go get ./...` - the change only affected test dependencies but, since the Go tool doesn't ignore the vendor folders, it breaks builds.

Upgrading to Go 1.9 fixes this, but I will only do that on a new release of Caddy.

**Comment by mholt** [comment]
Should be working now.
