### ISSUE TITLE
https://caddyserver.com/docs/caddyfile/directives/tls#mode has malformed table

### ISSUE THREAD

**Issue by ProactiveServices** [caddyserver/website#314]
The source markdown for the [caddyfile/directives/tls#mode](https://caddyserver.com/docs/caddyfile/directives/tls#mode) section checks out but the served HTML has mangled the table.

**Comment by francislavoie** [comment]
Thanks for spotting that! Fixed in 4411a7015ddfe393725ee8c4af43e0eb2b9a283e

The problem was inconsistent support for tab indentation within bullet lists. Using spaces instead fixes the problem.

Before:

![image](https://user-images.githubusercontent.com/2111701/230377382-b1fbf9b5-7188-40e0-9ead-30d90b407295.png)

After:

![image](https://user-images.githubusercontent.com/2111701/230377425-d3de3bff-4993-48a9-a891-564915fa99fb.png)
