### ISSUE TITLE
docs/json/apps/http/ not rendering content

### ISSUE THREAD

**Issue by chrislabarge** [caddyserver/website#318]
Upon visiting https://caddyserver.com/docs/json/apps/http/ I am no longer seeing any content. 

![caddyserver com_docs_json_apps_http_](https://user-images.githubusercontent.com/9273735/236523627-31f43c68-1b6a-4acd-a7f5-49d851744bbf.png)

**Comment by francislavoie** [comment]
We're aware 😓 the docs server is taking 2 minutes to respond all of a sudden. We're trying to figure out why.

**Comment by mholt** [comment]
Does it load after 2 minutes?

I checked the JSON docs but they were working. Maybe only non-cached values are hanging. Something with the DB is slow?

**Comment by chrislabarge** [comment]
Working again!

**Comment by mholt** [comment]
Yes, that page works -- because I let it load for 2 minutes, then it was cached, but I bet pages that aren't already cached by the docs server will hang for 2 minutes while it loads from the DB.

Very strange. I'm not sure why the DB would suddenly be hanging for 2 minutes. It's almost like there's a `sleep()` call going on.

**Comment by Xerkus** [comment]
I encountered this issue previously and just now as well.

May be change javascript populating page so it would print an instruction to wait and refresh page if it got nothing to show?
