### ISSUE TITLE
v2: Make JSON docuntation API server public

### ISSUE THREAD

**Issue by roblabla** [caddyserver/website#6]
I was going to try and see if I could fork this to make my own module documentation in the same vein as https://caddyserver.com/docs/json/apps/http/servers/routes/handle/authentication/. Looking at the source code, it seems the website does some requests to an API server providing the documentation, but I couldn't find this server's source. Am I looking at the wrong place? Would it be possible to document how we can make our own docs like this one?

**Comment by mholt** [comment]
It definitely is one-of-a-kind!

I haven't published this source... it's still a major WIP, and once I open it, it's a big maintenance burden because, well, open source :) Also, it's super niche. It really only works for Caddy 2 (and its modules), because Caddy 2 has a very unique architecture that I've not seen in any other Go programs.

But I hope to get around to working on it soon, at least! Right now my priority is Smallstep integration and finishing up a stable 2.0 release.

Closing, but feel free to continue discussion.

(To clarify, I do intend to expand the website more; you'll be able to use your Caddy account to add to the JSON documentation for your Caddy modules.)

**Comment by qrhfz** [comment]
README should say that json api docs server is not included. it was a bummer.
