### ISSUE TITLE
Why were v1 docs removed?

### ISSUE THREAD

**Issue by polarathene** [caddyserver/website#64]
Looking into Caddy via Google searches and links from communities including the forum with posts only a month or so old, I have come across v1 doc URLs. 

These fail to load as they're no longer hosted. One has to view the documentation section and scroll down to the bottom of the left sidebar to get a download link of the v1 docs archived.. I feel that was too soon. Even though I'm only interested in using v2, the current docs have been hit/miss on quality at presenting information. Some v1 docs also have no equivalent v2 yet until the feature is ported, while v1 may no longer be actively supported, I assume there are still users running v1.

Hosting v1 docs shouldn't be that much of a burden, although I'd advised a warning banner at the top of the pages to clearly communicate to users that these are v1 docs and they might want to access the v2 docs instead.

Alternatively, rather than fail, these routes should be captured and redirect to a v1 deprecation page that encourages adoption of v2 while providing a link to the v1 docs archive if hosting them is an issue. Not doing this, Google and any other indexers should be informed appropriately that this content is no longer available so they remove their indexes on it sooner?

**Comment by francislavoie** [comment]
Related issue: https://github.com/caddyserver/website/issues/30

> Even though I'm only interested in using v2, the current docs have been hit/miss on quality at presenting information.

Could you please give more specific examples so we can look to improve things? Vague statements like that aren't helpful on their own.

> Some v1 docs also have no equivalent v2 yet until the feature is ported

Feel free to open feature requests for anything that's missing, or if it was a v1 plugin, open an issue on the plugin repo to see if the author is willing to port it to v2.

> although I'd advised a warning banner at the top of the pages to clearly communicate to users that these are v1 docs and they might want to access the v2 docs instead.

We did have that for a time since the v2 site went up during the betas.

I'll let @mholt explain further.

**Comment by polarathene** [comment]
> Vague statements like that aren't helpful on their own.

I wanted to focus the issue on the v1 docs, rather than v2 docs.

> Feel free to open feature requests for anything that's missing

I'm not a v1 user myself, I did recently land on [this thread](https://caddy.community/t/caddy-v2-http-cache/8792) about http-cache in v2, the user linked to v1 docs only a month ago, so removal must have happened since then?

You replied in that thread linking to two projects and mentioning the plugin was WIP for v2. I'm too new to Caddy to have any feature requests just yet.

> We did have that for a time since the v2 site went up during the betas.

Yeah...but v2 only recently was released as stable within the past 6 months? I haven't been following it too closely. Seems a little soon to pull docs for v1 away like that, they already had a v1 path prefix, so I'm a bit confused why there was a decision to remove them, especially with the poor UX it now causes for new and existing users.

**Comment by polarathene** [comment]
> Could you please give more specific examples so we can look to improve things? 

Sure I'll try.

---

I am still new to Caddy and initial use case was wanting a quick local server to test caching behaviour of images, as the development server my project was using only allowed for `Cache-Control: public,max-age=0`.

I setup a Docker container fairly easily via the information on DockerHub, the Caddyfile documentation was less pleasant. Tried the documentation search field(powered by Algolia) but didn't find anything useful when looking for how to handle caching in Caddy from that. I realized I probably needed to look for something more generic like handling a header response, again I recall that being a bit confusing to find the right page.

I ended up with the following:

```
{
  auto_https off
}
:80

root * /usr/share/caddy

file_server
 
header Cache-Control max-age=60
```

Originally I had `public, max-age=60` but it didn't work as expected due to the space, the docs weren't very clear that quotes were required for Caddyfile syntax, when the value after `field` name included spaces. AFAIK this is a non-standard config file?(As in not a common format like JSON or TOML, but unique to Caddy?)

I had tried to look into how I might filter that specific resource types like images, there was this [`path_regex`](https://caddyserver.com/docs/caddyfile/matchers#path-regexp) which seems appropriate but wasn't clear how to utilize it correctly from the example. `path` seems slightly easier syntax but afaik can only wildcard to a single file extension, so a regex is the way to go? `path_regex` mentioned using what I think is called `placeholder` to refer to the match or a sub-match via numbers, due to the limited example I wasn't quite sure how to use it with the header directive.

Initial assumption:

```
# Nope, runtime error about bad config due to path_regexp
path_regexp static \.(css|js)$
header static Cache-Control "public, max-age=60"
# or
header {http.regexp.static} Cache-Control "public, max-age=60"
```

Eventually got it figured out, backtracking the docs to understand it needed to be defined in a "named" matcher block. Putting something between the header directive and the header field was also something that wasn't immediately clear to me from what I had landed on and was referencing on the docs at the time, I remember thinking if I needed something like a locations block for where root was defined to wrap in the scope for how/when this header directive is applied. And if the order of declarations was correct or not, if I'd need to use the route block I had seen in docs earlier, etc.

```
# Yep, name doesn't have any relevance here, 
# I assume it's meant to be useful only within the named matcher somehow
@assets {
  path_regexp static \.(css|js)$
}

header @assets Cache-Control "public, max-age=60"
```

---

Other than that, I recall jumping around the sidebar quite a bit trying to navigate it and find information on what I wanted to do. I remember HTTPS was being automatically redirected even though I only exposed port 80, which had me a bit confused, wasn't too difficult to find out how to disable it, although that global options at the top syntax was a bit odd. 

Documentation wise, I think Traefik does a pretty good job if you'd like a reference. Sorry I don't have much more to describe the experience. One other thing I think I recall wanting was a "reference" page like Traefik provides for their dynamic and static configs, it's like a fleshed out config example showing the various options with defaults assigned if any iirc. I would then have a good overview of the structure and layout/flow for the config, and could go lookup that information elsewhere in the docs if I needed more clarification. 

When looking into the Caddyfile, I recall several pages, that touched on a few things, or examples for common setups that were quite brief, but none were showing things like setting up headers for caching/compression or routes/nesting, etc, while those features themselves had some documentation, it was often barebones example and not always clear how to utilize it in the config as shown above. This could be my fault for diving in to get going ASAP instead of reading through documentation more thoroughly to grasp directives/matchers and such.

**Comment by polarathene** [comment]
https://caddyserver.com/docs/caddyfile/directives/header

Has numerous header examples which is nice, even has one for `Cache-Control` at the bottom, perhaps a case where one of the values is using more than `max-age` so that it's clear that if a space is included it needs quotes. I understand that is covered in the main [concepts](https://caddyserver.com/docs/caddyfile/concepts#tokens-and-quotes) section, but I was attempting to "run before I could walk" I guess?

```
route {
	header           Cache-Control max-age=3600
	header /static/* Cache-Control max-age=31536000
}
```

I think it was the first time I saw `route` used, but no route/path is provided, so I was a bit confused what was going on there.

No other examples show the usage of filtering to a resource type or path(or named matcher), so the `/static/*` didn't quite make sense to me what was going on there. The examples have complimentary text to briefly clarify some information about what they're demonstrating, but there isn't anything clarifying `/static/*` or how these two lines are working, or if the `route` is required. Perhaps because it's explained elsewhere and the user is expected to be familiar with all that already by this point if they progressed through the documentation as the author expected?

I'm not sure if the `route` block is required in my case since I'm not doing anything else, I assume the first header definition is defining a broad default, but the one with a path rule after has higher priority, presumably declaration order matters here, if the order was the other way around, would the 2nd declaration override it even though it's less specific?

```
header [<matcher>] [[+|-]<field> [<value>|<find>] [<replace>]] {
```

That is the only part that mentions the `<matcher>` which is not described below like the other values, presumably because a user would know/recognize that and the syntax of this definition. I cannot click the `<matcher>` text as a link to matcher docs, I'm not sure why it's rendered blue unlike the others

---

https://caddyserver.com/docs/quick-starts/https

This is pretty visible on the left sidebar under the quickstarts. It points out that by default HTTPS is enabled, it focuses on how this is beneficial but doesn't mention how to disable it by mentioning the global config `auto_https off` and linking to that page. 

As I started from Docker and was running a local instance, mapping port 80 to whatever port I want to access the container via browser such as port 8000 is ok, but I don't see how I'd map 443 to my container that it was redirecting me to, perhaps I had to alternatively configure Caddy to use a different HTTPS port and have it redirect to that instead.

I didn't need HTTPS so I didn't look into that being possible. Mentioning early, or within the note about HTTPS being enabled by default, that it can be disabled easily via `auto_https off` would be a better UX for discovering such.

---

https://caddyserver.com/docs/caddyfile/concepts

The visual description image at the top here is too noisy. I understand the colours and shapes are meant to help but it's initial impression is more complicated than helpful (that is, without even ingesting the content further, it's already uninviting). Breaking this a part into several images and some whitespace may help, rather than the colourful nesting and dense packing of information(highlights and regions rather) reducing the usefulness of breaking down the information.

I'm not sure if I described that right, I can see what the intent was, I do recall Traefik having visuals for some of their concepts that worked well, followed by snippet examples. They might have had some Medium articles that had other visuals regarding syntax breakdown, perhaps it's the choice or application of the colours in this Caddy document that is working against it's favor.

The document itself details the concepts pretty well and I probably should have read it first but the size of it was initially off-putting.

**Comment by polarathene** [comment]
```
route {
	header           Cache-Control max-age=3600
	header /static/* Cache-Control max-age=31536000
}
```

Tried without `route` directive and switched the declaration order, in both cases the one with the matcher only applies if it is 2nd, so `route` served no purpose in that example?

**Comment by Merith-TK** [comment]
Would like to add on that v1 docs had documentation somewhere in the article, even if it was linked to another website, about all the subdirectives/plugins, while v2 i have no clue how to use markdown without copying from the caddyfile and index.html files located here.

**Comment by mholt** [comment]
Sorry for taking a while to get on this, I've been behind in notifications for 2 weeks and finally have a small window to catch up.

I've read the discussion here, and there's a lot so I can't address it all, but I'll reply to some parts.

@polarathene 

> Hosting v1 docs shouldn't be that much of a burden, 

It is though. The v1 docs were not static, so they required an old and decaying backend server that was not compatible with v2 or the new database. Plus the use of templates were not compatible with v2 because, well, v2 is a breaking change. We would have had to continue running Caddy 1 + Caddy 2 + old DB + new DB + hacks to make everything work together, etc...

So, no, sorry, it was too much of a burden for a very very small open source project.

The archive you can download is an enumeration of the various plugin docs from the old DB, frozen in time.

> although I'd advised a warning banner at the top of the pages to clearly communicate to users that these are v1 docs and they might want to access the v2 docs instead.

We had that for about 6 months: a big, red bar that said something like, "These are disappearing soon, please upgrade to v2."

> Alternatively, rather than fail, these routes should be captured and redirect to a v1 deprecation page that encourages adoption of v2 while providing a link to the v1 docs archive if hosting them is an issue.

That's exactly what we did.

> they already had a v1 path prefix,

Those were the result of temporary redirects during the transition period. The original URLs did not have /v1.

> Seems a little soon to pull docs for v1 away like that

Huh? But as you've noticed, the v1 docs are still available for now: https://caddyserver.com/caddy-v1-docs-archive.tar.gz

> I haven't been following it too closely.

This is the unfortunate part about open source: most people don't follow their projects of interest close enough, so when something changes after 1+ years of development, _then_ they react, but the best time for that would be _before_ the big changes. Caddy 2 was not developed behind a curtain, we've had the source code out for about 10+ months before the 2.0 tag. There was plenty of time to be aware of what was coming and get involved. But almost nobody did. (I'm grateful to those who did, though.)

> Originally I had public, max-age=60 but it didn't work as expected due to the space, the docs weren't very clear that quotes were required for Caddyfile syntax, when the value after field name included spaces. AFAIK this is a non-standard config file?(As in not a common format like JSON or TOML, but unique to Caddy?)

I think they're really quite clear on this point? https://caddyserver.com/docs/caddyfile/concepts#tokens-and-quotes

<img width="956" alt="Screen Shot 2020-07-31 at 6 10 56 PM" src="https://user-images.githubusercontent.com/1128849/89089160-37cdb680-d359-11ea-9a22-614494301562.png">

> Eventually got it figured out, backtracking the docs to understand it needed to be defined in a "named" matcher block. 

Basically, all matchers go inside a named matcher block. But because path matchers are used so frequently, they can usually be inlined.

>  although that global options at the top syntax was a bit odd.

True; to be fair, though, you don't _have_ to use the Caddyfile if you don't like it. You can literally use [any config format you want](https://caddyserver.com/docs/config-adapters).

>  One other thing I think I recall wanting was a "reference" page like Traefik provides for their dynamic and static configs, it's like a fleshed out config example showing the various options with defaults assigned if any iirc.

You mean like this? https://caddyserver.com/docs/json/

That's literally every single config parameter that is available:

<img width="737" alt="Screen Shot 2020-07-31 at 6 18 19 PM" src="https://user-images.githubusercontent.com/1128849/89089380-3bae0880-d35a-11ea-880e-245fe411172b.png">

> I think it was the first time I saw route used, but no route/path is provided, so I was a bit confused what was going on there. ... I'm not sure if the route block is required in my case since I'm not doing anything else, I assume the first header definition is defining a broad default, but the one with a path rule after has higher priority, presumably declaration order matters here, if the order was the other way around, would the 2nd declaration override it even though it's less specific? ... Tried without route directive and switched the declaration order, in both cases the one with the matcher only applies if it is 2nd, so route served no purpose in that example?

That particular example is explained fully in our wiki, which is a community-contributed extension to our docs: https://caddy.community/t/composing-in-the-caddyfile/8291?u=matt

@Merith-TK 

> Would like to add on that v1 docs had documentation somewhere in the article, even if it was linked to another website, about all the subdirectives/plugins, while v2 i have no clue how to use markdown without copying from the caddyfile and index.html files located here.

I gotchu :)

<img width="968" alt="Screen Shot 2020-07-31 at 5 46 08 PM" src="https://user-images.githubusercontent.com/1128849/89089656-998f2000-d35b-11ea-9ea5-79aa31cfbe9f.png">

Sometimes it really is just that easy!

----

In summary, thanks for typing all that up. I felt your experience was very relatable. It's basically the same process I go through when I learn new software, too. What more could you want? You get to know the ins-and-outs of both the documentation and the software, gain valuable experience, and learn how it works as a whole as well as for what you need. Sure, it takes time. We put a lot of time and effort into writing this free software for you to use, and believe it or not we also sink a lot of time into the docs and supporting services. We expect the same of users, since we're all professionals here: spend time reading the docs, tinkering, experimenting, and learning how the product works. We're always interested in making our docs better. But first we need to be convinced that complaints about the docs aren't just another case of people not reading them, which we get all too often. Caddy is not a child's toy, it will take some time to truly master its intricacies: something I haven't even done yet. I'm still amazed every so often when I see @francislavoie or @whitestrake or @Mohammed90 whip out a config that solves a problem more elegantly than I could have come up with.

**Comment by polarathene** [comment]
> I think they're really quite clear on this point? https://caddyserver.com/docs/caddyfile/concepts#tokens-and-quotes

Yes, they are. It's just that I didn't end up seeing that for a while due to the amount of upfront reading when I just wanted to have a server up and running quickly (which I think Caddy promotes itself for that UX?), and do what I would assume isn't all that uncommon and add a `Cache-Control` response header.

So I get Caddy up and running and able to serve the website and content easily enough, awesome. Then I look for stuff about headers, specifically my first thought was that there might be documentation on caching with Caddy, so I give the sidebar a quick look, maaaaybe there's something about it there, but rather than digging through that I'll see if the search feature is helpful:

![Screenshot_20200801_191000](https://user-images.githubusercontent.com/5098581/89096462-06252000-d42b-11ea-85c7-1291d335209f.png)

I guess not so much in this case..ah, probably should go for something more generic, like header config... well sidebar doesn't have anything that stands out, try the search field again:

![Screenshot_20200801_191544](https://user-images.githubusercontent.com/5098581/89096533-69af4d80-d42b-11ea-94bb-0b776bfa24a9.png)

Well, looks like one of those results might be it, but they sure do use up a lot of vertical space and don't provide much insight to their relevance, not sure what these http modules for headers handlers and matchers are yet(at the time this would have been my thought process), I'll give the `header > header | header` result a go.

Great description once arriving on [the header directive page](https://caddyserver.com/docs/caddyfile/directives/header#header), Syntax was a bit much and not particularly friendly at first glance, but still somewhat useful, before trying to ingest that, lets see if there is some examples, yep! There's even one about `Cache-Control` at the bottom, not sure what that `route` thing is just yet but sweet, lets see if I can get that working.

It's only at that point that I looked up the Caddyfile as a way to configure the server. I had come from DockerHub which made initial setup easy, it had made me aware of the Caddyfile if I wanted my own changes added, I had no idea what the standard config looked like though, I found plenty of snippets in the docs, but ended up looking for what the Docker image was defaulting to on github and starting from there. 

Not having learned what directives were had me wondering where exactly I'd put that header line, and if I needed it wrapped within `route`. It was around that point that I think I realized I would need to spend more time learning how Caddy config works. Still I had managed to read enough to get that working, and remember learning about matchers / directives, but hadn't run into the token quotes section.

Minor improvement to the docs might be to have a cache-control example without the `route` directive, using a named matcher and a value with spaces so it's more implicitly clear that they're required, easier to learn through example and if curious run through the docs to see if there's something about the quoting mentioned / explained afterwards.

---

> You mean like this? https://caddyserver.com/docs/json/

Yes, might have been less discoverable/obvious to me at the time since it was under the label "JSON Config Structure", whereas I might have been thinking to see "Reference" instead of "Structure", I understand it's under a "REFERENCE" section title, but it's positioned between "Modules" and "Automatic HTTPS", if it's meant to be related to the Caddyfile in anyway, I did not get that impression with the hierarchy.

Traefik seems to handle that [a bit better](https://docs.traefik.io/reference/static-configuration/file/). Although I really like how the Caddy docs has those mouse-over notes.

Is there something similar for the Caddyfile?

---

> We're always interested in making our docs better. But first we need to be convinced that complaints about the docs aren't just another case of people not reading them, which we get all too often.

I understand that, I'm just sharing how I approached the docs as a new user where the typical happy path for a new user wasn't followed, if other users chime in with similar experiences like mine, it's not necessarily a case of "not reading the docs" so much as it is the way they're being read. 

Yes, the right information is generally there, and I accept fault for not making enough time upfront to go through them properly from the start before giving Caddy a try.

---

Thanks for taking the time to respond. Caddy is quite nice!
